//export constants as int

export const SCREENS = {
  HOME: 0,
  CREATE: 1,
  JOIN: 2,
  WAITING: 3,
  GAME: 4,
  SCORE: 5,
};

export const ROOM_SETTINGS = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 10,
  MAX_QUESTIONS_PER_REPORT: 5,
};

export const GAME_SETTINGS = {
  MAX_QUESTIONS_PER_REPORT: 5,
  MAX_TIME_PER_QUESTION: 30,
  MAX_TIME_PER_REPORT: 10,
  MAX_TIME_PER_GAME: 1800,
};
